<?php
 $aik =  array (
  'title' => '七途导航 - 七途导航网 www.7tu.me',
  'keywords' => '七途导航网，七途网络，七途导航，七途网，七途',
  'description' => '七途导航网为大家提供七途网络旗下小工具!',

  '1zi' => '微晓V支付',
  '2zi' => '等待添加',
  '3zi' => '等待添加',
  '4zi' => '等待添加',
  '5zi' => '等待添加',
  '6zi' => '等待添加',
  '7zi' => '等待添加',
  '8zi' => '等待添加',
  '9zi' => '等待添加',
  '10zi' => '等待添加',
  '11zi' => '等待添加',
  '12zi' => '等待添加',
  '13zi' => '等待添加',
  '14zi' => '等待添加',
  '15zi' => '等待添加',
  '16zi' => '等待添加',
  '17zi' => '等待添加',
  '18zi' => '等待添加',

  '1lianjie' => 'https://vxvpay.cn',
  '2lianjie' => 'http://www.7tu.me',
  '3lianjie' => 'http://www.7tu.me',
  '4lianjie' => 'http://www.7tu.me',
  '5lianjie' => 'http://www.7tu.me',
  '6lianjie' => 'http://www.7tu.me',
  '7lianjie' => 'http://www.7tu.me',
  '8lianjie' => 'http://www.7tu.me',
  '9lianjie' => 'http://www.7tu.me',
  '10lianjie' => 'http://www.7tu.me',
  '11lianjie' => 'http://www.7tu.me',
  '12lianjie' => 'http://www.7tu.me',
  '13lianjie' => 'http://www.7tu.me',
  '14lianjie' => 'http://www.7tu.me',
  '15lianjie' => 'http://www.7tu.me',
  '16lianjie' => 'http://www.7tu.me',
  '17lianjie' => 'http://www.7tu.me',
  '18lianjie' => 'http://www.7tu.me',

  'admin_name' => 'admin',
  'admin_pass' => '3ceb0e9fb16f8673c35f707e8657124a',
  'logo_dh' => 'http://a.weixincun.net/img/logo.png',
  
);
?>